document.write(typeof(someNumber) + "<br/>"+
    typeof(otherNumber) + "<br/>"+ 
    typeof(someBoolean) + "<br/>"+
    typeof(otherBoolean) + "<br/>"+
    typeof(someString) + "<br/>"+
    typeof(otherString) + "<br/>"+
    typeof(someObject) + "<br/>"+
    typeof(someArray) + "<br/>"+
    typeof(otherArray) + "<br/>"+
    typeof(someFunction) + "<br/>"+
    typeof(quotation) + "<br/>");